session_name: development_env
windows:
  - window_name: compile
    layout: even-horizontal
    panes:
      - shell_command:
        - cd packages/app
        - yarn serve
      - shell_command:
        - cd packages/server
        - yarn serve:dev
  - window_name: infrastructure
    panes:
      - docker-compose up
