version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  s3-storage:
    image: minio
    ports:
      - 9000:9000
      - 9001:9001
